/*
 * Host tool: emit the provisioned data blob (as a C array) for one integration
 * scenario. Uses the same src/ modules the device runs.
 *
 *   gen_fixture good              -> should BOOT
 *   gen_fixture rollback_replay   -> old signed image vs an advanced counter
 *   gen_fixture tampered_counter  -> a flipped bit in the newest counter page
 *   gen_fixture cloned_flash      -> device 1's helper + flash on device 2
 */

#include "fixture.h"

#include "puf/puf_sim.h"
#include "fuzzy/fuzzy_extractor.h"
#include "kdf/kdf.h"
#include "rollback/rollback.h"
#include "secure_boot/secure_boot.h"

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int PQCLEAN_MLDSA44_CLEAN_crypto_sign_keypair(uint8_t *pk, uint8_t *sk);

#define BLOCKS       128u
#define REP          15u
#define GOOD_BER_PPM 20000u /* 2% */
#define BODY_LEN     96u
#define COUNTER      3u

static void put32(uint8_t *p, uint32_t v)
{
    for (int i = 0; i < 4; i++) {
        p[i] = (uint8_t)(v >> (8 * i));
    }
}

static void emit(const uint8_t *blob, size_t n)
{
    printf("/* generated by integration/gen_fixture -- do not edit */\n");
    printf("const unsigned char fixture_blob[] = {\n");
    for (size_t i = 0; i < n; i++) {
        printf("0x%02x,", blob[i]);
        if ((i % 16) == 15) {
            printf("\n");
        }
    }
    printf("\n};\n");
    printf("const unsigned int fixture_blob_len = %zuu;\n", n);
}

int main(int argc, char **argv)
{
    if (argc < 2) {
        fprintf(stderr, "usage: gen_fixture <scenario>\n");
        return 64;
    }
    const char *scen = argv[1];

    uint64_t fw_version = 3;
    int tamper_counter = 0;
    int clone = 0;

    if (strcmp(scen, "good") == 0) {
        /* defaults */
    } else if (strcmp(scen, "rollback_replay") == 0) {
        fw_version = 2; /* validly signed, but below the counter */
    } else if (strcmp(scen, "tampered_counter") == 0) {
        tamper_counter = 1;
    } else if (strcmp(scen, "cloned_flash") == 0) {
        clone = 1;
    } else {
        fprintf(stderr, "unknown scenario: %s\n", scen);
        return 64;
    }

    const fuzzy_params fp = { .blocks = BLOCKS, .rep = REP };
    size_t helper_len = fuzzy_response_bytes(fp); /* 240 */

    /* --- provision device 1 --- */
    uint8_t w_clean[FUZZY_MAX_RESPONSE_BYTES];
    puf_sim_response(1, w_clean, helper_len);

    uint8_t rnd[16];
    for (int i = 0; i < 16; i++) {
        rnd[i] = (uint8_t)i;
    }
    uint8_t helper[FUZZY_MAX_RESPONSE_BYTES];
    uint8_t key_material[32];
    fuzzy_gen(fp, w_clean, helper_len, rnd, sizeof rnd, helper, helper_len,
              key_material, sizeof key_material);

    uint8_t rb_key[ROLLBACK_KEY_BYTES];
    rot_kdf_derive(key_material, sizeof key_material,
                   (const uint8_t *)"rollback-auth-key", 17, rb_key, sizeof rb_key);

    rollback_store rb;
    rollback_enroll(&rb, rb_key, 0);
    rollback_update(&rb, rb_key, COUNTER, 0); /* counter = 3, newest page is 1 */
    if (tamper_counter) {
        rb.page[1][8] ^= 0x01;
    }

    /* --- vendor key + signed firmware --- */
    uint8_t spk[SB_PUBKEY_BYTES], ssk[SB_SECKEY_BYTES];
    PQCLEAN_MLDSA44_CLEAN_crypto_sign_keypair(spk, ssk);

    uint8_t body[BODY_LEN];
    for (unsigned i = 0; i < BODY_LEN; i++) {
        body[i] = (uint8_t)(i * 5 + 3);
    }
    static uint8_t fw[8192];
    size_t fw_len = 0;
    if (secure_boot_pack(fw_version, body, BODY_LEN, ssk, fw, sizeof fw, &fw_len) != 0) {
        fprintf(stderr, "secure_boot_pack failed\n");
        return 70;
    }

    uint32_t blob_device_id = clone ? 2u : 1u;

    /* --- serialize --- */
    size_t n = 28 + helper_len + 64 + 64 + FIXTURE_OTP_BYTES + fw_len;
    uint8_t *blob = malloc(n);
    if (!blob) {
        return 71;
    }
    blob[0] = 'I'; blob[1] = 'T'; blob[2] = 'G'; blob[3] = '1';
    put32(blob + 4, blob_device_id);
    put32(blob + 8, GOOD_BER_PPM);
    put32(blob + 12, BLOCKS);
    put32(blob + 16, REP);
    put32(blob + 20, (uint32_t)helper_len);
    put32(blob + 24, (uint32_t)fw_len);
    size_t off = 28;
    memcpy(blob + off, helper, helper_len);           off += helper_len;
    memcpy(blob + off, rb.page[0], 64);               off += 64;
    memcpy(blob + off, rb.page[1], 64);               off += 64;
    memcpy(blob + off, spk, FIXTURE_OTP_BYTES);       off += FIXTURE_OTP_BYTES;
    memcpy(blob + off, fw, fw_len);                   off += fw_len;

    emit(blob, n);
    free(blob);
    return 0;
}
